name: Release to PyPI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose pypi environment to publish to"
        required: true
        default: "testpypi"
        type: choice
        options:
          - "testpypi"
          - "pypi"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-14"
          - "windows-latest"
        python:
          - "cp310"
          - "cp311"
          - "cp312"
          - "cp313"

    runs-on: ${{ matrix.os }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build wheels action
        uses: ./.github/actions/build-wheel
        with:
          python: ${{ matrix.python }}
          os: ${{ matrix.os }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Twine
        run: pip install --upgrade pip twine

      - name: Upload to PyPI or TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ inputs.environment == 'pypi' && secrets.PYPI_TOKEN || secrets.PYPI_TEST_TOKEN }}
        run: twine upload --verbose --repository ${{ inputs.environment }} wheelhouse/*.whl
